//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangMayTinh.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;

    public partial class Chip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chip()
        {
            this.MayVTs = new HashSet<MayVT>();
        }

        public string MaChip { get; set; }
        public string TenChip { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MayVT> MayVTs { get; set; }
        public string autoGenCode()
        {
            using (var context = new Entity())
            {
                var lastQuery = context.Chips.OrderByDescending(p => p.MaChip).FirstOrDefault();
                MaChip = lastQuery.MaChip;

                if (lastQuery != null)
                {
                    // Xử lý lastQuery
                    int temp = Convert.ToInt32(MaChip.Substring(2)) + 1;
                    string newcode = "C" + temp.ToString();
                    return newcode;
                }
                else
                {
                    MessageBox.Show("Cơ sở dữ liệu chưa có dữ liệu", "Lỗi tìm kiếm", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    return "C0";
                }
            }
        }
    }
}