//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangMayTinh.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;

    public partial class HoaDonBan
    {
        Entity db = new Entity();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBan()
        {
            this.ChiTietHDBs = new HashSet<ChiTietHDB>();
        }
        public string autoGenCode()
        {
            using (var context = new Entity())
            {
                var lastQuery = context.HoaDonBans.OrderByDescending(p => p.MaHDB).FirstOrDefault();
                MaHDB = lastQuery.MaHDB;

                if (lastQuery != null)
                {
                    // Xử lý lastQuery
                    int temp = Convert.ToInt32(MaHDB.Substring(3)) + 1;
                    string code = "";
                    if (temp < 10)
                    {
                        code = "0" + temp.ToString();
                    }
                    else
                    {
                        code= temp.ToString();
                    }
                    string newcode = "HDB" + code;
                    return newcode;
                }
                else
                {
                    MessageBox.Show("Cơ sở dữ liệu chưa có dữ liệu", "Lỗi tìm kiếm", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    return "HDB0";
                }
            }
        }
        public HoaDonBan addData(DateTime ngayban, String maNV, String maKH, Double TongTien)
        {

            HoaDonBan hoaDonBan = new HoaDonBan() { MaHDB = autoGenCode(), NgayBan = ngayban, MaNV = maNV, MaKH = maKH, TongTien = TongTien };
            db.HoaDonBans.Add(hoaDonBan);
            db.SaveChanges();
            return hoaDonBan;
        }

        public string MaHDB { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string MaNV { get; set; }
        public string MaKH { get; set; }
        public Nullable<double> TongTien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDB> ChiTietHDBs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
