//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangMayTinh.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;

    public partial class KhachHang
    {
        Entity db=new Entity();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
        public string autoGenCode()
        {
                var lastQuery = db.KhachHangs.OrderByDescending(p => p.MaKH).FirstOrDefault();
                MaKH = lastQuery.MaKH;

                if (lastQuery != null)
                {
                    // Xử lý lastQuery
                    int temp = Convert.ToInt32(MaKH.Substring(2)) + 1;
                    string code = "";
                    if (temp < 10)
                    {
                        code = "0" + temp.ToString();
                    }
                    else
                    {
                        code = temp.ToString();
                    }
                    string newcode = "KH" + code;
                    return newcode;
                }
                else
                {
                    MessageBox.Show("Cơ sở dữ liệu chưa có dữ liệu", "Lỗi tìm kiếm", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    return "KH0";
                }
        }
        public KhachHang addData(KhachHang a)
        {

            KhachHang KhachHang = new KhachHang() { MaKH = autoGenCode(), TenKH=a.TenKH,DiaChi=a.DiaChi,Dienthoai=a.Dienthoai  };
            db.KhachHangs.Add(KhachHang);
            db.SaveChanges();
            return KhachHang;
        }

        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string Dienthoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
    }
}
