//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangMayTinh.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;

    public partial class MayVT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MayVT()
        {
            this.ChiTietHDBs = new HashSet<ChiTietHDB>();
            this.ChiTietHDNs = new HashSet<ChiTietHDN>();
        }
        public string autoGenCode()
        {
            using (var context = new Entity())
            {
                var lastQuery = context.MayVTs.OrderByDescending(p => p.MaMVT).FirstOrDefault();
                MaMVT = lastQuery.MaMVT;

                if (lastQuery != null)
                {
                    // Xử lý lastQuery
                    int temp = Convert.ToInt32(MaMVT.Substring(3)) + 1;
                    string code = "";
                    if (temp < 10)
                    {
                        code = "0" + temp.ToString();
                    }
                    string newcode = "MVT" + code;
                    return newcode;
                }
                else
                {
                    MessageBox.Show("Cơ sở dữ liệu chưa có dữ liệu", "Lỗi tìm kiếm", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    return "HDB0";
                }
            }
        }
        public void addData(string TenMVT, string Loai, string Chip, string OC,
            string DL, string TD, string OCD, string MH, string CoMH, string Chuot,
            string BP, string USB, string Ram, string Loa, string HSX, double giaNhap, double giaBan,
            DateTime baoHanh, byte[] imageData , string ghiChu)
        {
            using (var db = new Entity())
            {
                MayVT mayVT = new MayVT() { MaMVT = autoGenCode(),TenMVT=TenMVT, MaLm = Loai, MaChip = Chip, MaOC = OC,
                MaDL=DL, MaTD=TD,MaO=OCD,MaMH=MH,MaCo=CoMH,MaChuot=Chuot,MaBP=BP,MaOUSB=USB,MaR=Ram,
                MaLoa=Loa,MaHSX=HSX,Gianhap=giaNhap,Giaban=giaBan,ThoiGianBH=baoHanh,Anh=imageData,Ghichu=ghiChu};
                db.MayVTs.Add(mayVT);
                db.SaveChanges();
            }
        }

        public string MaMVT { get; set; }
        public string TenMVT { get; set; }
        public string MaLm { get; set; }
        public string MaChip { get; set; }
        public string MaOC { get; set; }
        public string MaDL { get; set; }
        public string MaTD { get; set; }
        public string MaO { get; set; }
        public string MaMH { get; set; }
        public string MaCo { get; set; }
        public string MaChuot { get; set; }
        public string MaBP { get; set; }
        public string MaOUSB { get; set; }
        public string MaR { get; set; }
        public string MaLoa { get; set; }
        public string MaHSX { get; set; }
        public Nullable<double> Gianhap { get; set; }
        public Nullable<double> Giaban { get; set; }
        public Nullable<System.DateTime> ThoiGianBH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public byte[] Anh { get; set; }
        public string Ghichu { get; set; }
    
        public virtual BanPhim BanPhim { get; set; }
        public virtual Chip Chip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDB> ChiTietHDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDN> ChiTietHDNs { get; set; }
        public virtual Chuot Chuot { get; set; }
        public virtual CoMH CoMH { get; set; }
        public virtual Dungluong Dungluong { get; set; }
        public virtual HangSX HangSX { get; set; }
        public virtual Loa Loa { get; set; }
        public virtual LoaiMay LoaiMay { get; set; }
        public virtual ManHinh ManHinh { get; set; }
        public virtual OCD OCD { get; set; }
        public virtual OCung OCung { get; set; }
        public virtual USB USB { get; set; }
        public virtual Ram Ram { get; set; }
        public virtual TocDo TocDo { get; set; }
    }
}
