//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangMayTinh.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;

    public partial class NhaCC
    {
        Entity db = new Entity();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCC()
        {
            this.HoaDonNhaps = new HashSet<HoaDonNhap>();
        }
        public string autoGenCode()
        {
            var lastQuery = db.NhaCCs.OrderByDescending(p => p.MaNCC).FirstOrDefault();
            MaNCC = lastQuery.MaNCC;

            if (lastQuery != null)
            {
                // Xử lý lastQuery
                int temp = Convert.ToInt32(MaNCC.Substring(3)) + 1;
                string code = "";
                if (temp < 10)
                {
                    code = "0" + temp.ToString();
                }
                else
                {
                    code = temp.ToString();
                }
                string newcode = "NCC" + code;
                return newcode;
            }
            else
            {
                MessageBox.Show("Cơ sở dữ liệu chưa có dữ liệu", "Lỗi tìm kiếm", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                return "NCC0";
            }
        }
        public NhaCC addData(NhaCC a)
        {

            NhaCC NhaCC = new NhaCC() { MaNCC = autoGenCode(), TenNCC = a.TenNCC, DiaChi = a.DiaChi, Dienthoai = a.Dienthoai };
            db.NhaCCs.Add(NhaCC);
            db.SaveChanges();
            return NhaCC;
        }

        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public string Dienthoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
    }
}
