//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangMayTinh.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Forms;

    public partial class NhanVien
    {
        Entity db= new Entity();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
            this.HoaDonNhaps = new HashSet<HoaDonNhap>();
        }
        public string autoGenCode()
        {
            var lastQuery = db.NhanViens.OrderByDescending(p => p.MaNV).FirstOrDefault();
            MaNV = lastQuery.MaNV;

            if (lastQuery != null)
            {
                // Xử lý lastQuery
                int temp = Convert.ToInt32(MaNV.Substring(3)) + 1;
                string code = "";
                if (temp < 10)
                {
                    code = "0" + temp.ToString();
                }
                else
                {
                    code = temp.ToString();
                }
                string newcode = "NV" + code;
                return newcode;
            }
            else
            {
                MessageBox.Show("Cơ sở dữ liệu chưa có dữ liệu", "Lỗi tìm kiếm", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                return "NV0";
            }
        }
        public NhanVien addData(NhanVien a)
        {

            NhanVien NhanVien = new NhanVien() { MaNV = autoGenCode(), TenNV = a.TenNV,NgaySinh=a.NgaySinh, Gioitinh=a.Gioitinh, Dienthoai = a.Dienthoai };
            db.NhanViens.Add(NhanVien);
            db.SaveChanges();
            return NhanVien;
        }

        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Gioitinh { get; set; }
        public string Dienthoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual loginAccout loginAccout { get; set; }
    }
}
